
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: "tu_password_segura"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    command: [
      "postgres",
      "-c", "wal_level=logical",
      "-c", "max_replication_slots=10",
      "-c", "max_wal_senders=10"
    ]
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - supabase_net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  gotrue:
    image: supabase/gotrue:v2.151.0
    restart: always
    environment:
      GOTRUE_DB_DRIVER: "postgres"
      GOTRUE_DB_DATABASE_URL: "postgresql://postgres:tu_password_segura@postgres:5432/postgres"
      GOTRUE_SITE_URL: "https://tu-dominio.com"
      GOTRUE_JWT_SECRET: "p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6"
      GOTRUE_LOG_LEVEL: "info"
      API_EXTERNAL_URL: "http://localhost:9999"
    depends_on:
      - postgres
    networks:
      - supabase_net
    ports:
      - "9999:9999"

  postgrest:
    image: postgrest/postgrest:v12.0.1
    restart: always
    environment:
      PGRST_DB_URI: "postgresql://postgres:tu_password_segura@postgres:5432/postgres"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "anon"
      PGRST_JWT_SECRET: "p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6"
      PGRST_SERVER_PORT: "3000"
    depends_on:
      - postgres
    networks:
      - supabase_net
    ports:
      - "3000:3000"

  realtime:
    image: supabase/realtime:v2.25.50
    restart: always
    environment:
      DB_HOST: "postgres"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "tu_password_segura"
      DB_PORT: 5432
      PORT: 4000
      JWT_SECRET: "clave_jwt_segura_y_larga"
      SECRET_KEY_BASE: "p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6"
      APP_NAME: "realtime"
      FLY_APP_NAME: "realtime"
    depends_on:
      - postgres
    networks:
      - supabase_net
    ports:
      - "4000:4000"

  storage:
    image: supabase/storage-api:v0.46.4
    restart: always
    environment:
      ANON_KEY: "p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6"
      SERVICE_KEY: "p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6"
      POSTGREST_URL: "http://postgrest:3000"
      DATABASE_URL: "postgresql://postgres:tu_password_segura@postgres:5432/postgres"
      FILE_SIZE_LIMIT: 52428800 # 50 MB
      PGRST_JWT_SECRET: "p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6"
      FILE_STORAGE_BACKEND_PATH: "/var/lib/storage"
    depends_on:
      - postgres
      - postgrest
    networks:
      - supabase_net
    ports:
      - "8080:5000"
    volumes:
      - storage-data:/var/lib/storage

  studio:
    image: supabase/studio:20240326-5e5586d
    restart: always
    environment:
      NEXT_PUBLIC_SUPABASE_URL: "http://localhost:3000"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6p4Q9xLm2T7vB1zN6"
    depends_on:
      - postgrest
      - gotrue
      - realtime
      - storage
    networks:
      - supabase_net
    ports:
      - "3001:3000"

volumes:
  pgdata:
  storage-data:

networks:
  supabase_net:
    driver: bridge
