version: '3.4'

services:
  samba:
    image: dperson/samba:latest
    environment:
      TZ: 'America/Panama'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./data:/mnt:z
      - ./comun:/mnt2:z
    command: '-s "Mount;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "bob;bobpasswd" -p'

networks:
  default: