version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db_core
      POSTGRES_USER: user_core
      POSTGRES_PASSWORD: *Ch1r1qu1
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
