services:
  wg-easy:
    container_name: wg-easy
    image: weejewel/wg-easy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=200.124.16.134
      - PASSWORD=javila@1234  # Cambia esto por seguridad
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.2
      - WG_DEFAULT_DNS=8.8.8.8
      - LANG=es
    ports:
      - "51820:51820/udp"  # Puerto WireGuard
      - "52821:51821/tcp"  # Interfaz web
    volumes:
      - ./config:/etc/wireguard
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
#windows
#Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" -Name "IPEnableRouter" -Value 1
